export const Photo1 = '/images/Photo1.jpg'
export const Photo2 = '/images/Photo2.jpg'
export const Photo3 = '/images/Photo3.jpg'
export const Photo5 = '/images/Photo5.jpg'
export const Logo = '/images/PostLogo5.png'
