export const THEMES = [
  'bootstrap4-light-blue',
  'bootstrap4-light-purple',
  'bootstrap4-dark-blue',
  'bootstrap4-dark-purple',
  'md-light-indigo',
  'md-light-deeppurple',
  'md-dark-indigo',
  'md-dark-deeppurple',
  'mdc-light-indigo',
  'mdc-light-deeppurple',
  'mdc-dark-indigo',
  'mdc-dark-deeppurple',
  'tailwind-light',
  'fluent-light',
  'lara-light-blue',
  'lara-light-indigo',
  'lara-light-purple',
  'lara-light-teal',
  'lara-dark-blue',
  'lara-dark-indigo',
  'lara-dark-purple',
  'lara-dark-teal',
  'soho-light',
  'soho-dark',
  'viva-light',
  'viva-dark',
] as const
